### ISSUE TITLE
wield dm_control.rl.control.PhysicsError when running vmail dm_control dmc_walker_stand

### ISSUE THREAD

**Issue by fokx** [rmrafailov/VMAIL#2]
I changed the config to use walker_stand expert data,
```python
config.task = 'dmc_walker_stand'
config.logdir = pathlib.Path('walker_stand_logdir')
config.model_datadir = pathlib.Path('walker_stand_model_data')
config.policy_datadir = pathlib.Path('walker_stand_policy_data')
config.expert_datadir = pathlib.Path('walker_stand_expert')
```
When I run vmail.py, it aborted after several training steps with the error 'dm_control.rl.control.PhysicsError:Physics state is invalid'.
```shell
[14000] expl_amount 0.3 / model_grad_norm nan / discriminator_norm nan / value_grad_norm 10.5 / actor_grad_norm 0.1 / prior_ent 103.9 / post_ent 1.3 / expert_d nan / policy_d 0.4 / max_policy_d 0.6 / rewards 0.4 / image_loss 122644302965768192.0 / div 75601088086016.0 / model_loss 122719902980112384.0 / expert_loss nan / policy_loss -0.6 / discriminator_loss nan / discriminator_penalty nan / value_loss 1.7 / actor_loss -2.4 / action_ent -92.7 / fps 5.2
Test episode of length 1000 with return 163.4.
Start collection.
Train episode of length 1000 with return 149.5.
Start evaluation.
Training for 200 steps.
[15000] expl_amount 0.3 / model_grad_norm nan / discriminator_norm nan / value_grad_norm 10.7 / actor_grad_norm 0.1 / prior_ent 105.9 / post_ent -8.3 / expert_d 0.6 / policy_d 0.4 / max_policy_d 0.6 / rewards 0.4 / image_loss 37099197358407680.0 / div 8276778418176.0 / model_loss 37107473760387072.0 / expert_loss -502834048.0 / policy_loss -0.5 / discriminator_loss 82440532736287228001048484556832768.0 / discriminator_penalty 82440532736287228001048484556832768.0 / value_loss 1.7 / actor_loss -2.5 / action_ent -94.0 / fps 5.3
python-BaseException
WARNING:absl:Unknown warning type Time = 0.0000.
Traceback (most recent call last):
  File "/home/liu/.miniconda3/envs/vmail/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/liu/.miniconda3/envs/vmail/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 332, in check_invalid_state
    raise _control.PhysicsError(message)
dm_control.rl.control.PhysicsError: Physics state is invalid. Warning(s) raised: mjWARN_BADCTRL

Process finished with exit code 1
```

**Comment by SiyuanLee** [comment]
Hi, I have met the same problem. Have you fixed it? I guess that this problem is related to the NaN loss error.
